import messages from './message-compiled';

const {
  JsonObjectMessage,
  UnreadTuple,
  LogItem,
  LoginCommand,
  DataCommand,
  SessionCommand,
  ErrorCommand,
  DirectCommand,
  AckCommand,
  UnreadCommand,
  ConvCommand,
  RoomCommand,
  LogsCommand,
  RcpCommand,
  ReadTuple,
  MaxReadTuple,
  ReadCommand,
  PresenceCommand,
  ReportCommand,
  GenericCommand,
  CommandType,
  OpType,
  StatusType,
} = messages.push_server.messages;

export {
  JsonObjectMessage,
  UnreadTuple,
  LogItem,
  LoginCommand,
  DataCommand,
  SessionCommand,
  ErrorCommand,
  DirectCommand,
  AckCommand,
  UnreadCommand,
  ConvCommand,
  RoomCommand,
  LogsCommand,
  RcpCommand,
  ReadTuple,
  MaxReadTuple,
  ReadCommand,
  PresenceCommand,
  ReportCommand,
  GenericCommand,
  CommandType,
  OpType,
  StatusType,
};
